---
- hosts: web
  user: ubuntu
  tasks:
    - name: Update all Ubuntu packages
      become: yes
      apt:
        upgrade: "dist"
      when: ansible_distribution == 'Ubuntu'

    - name: Install required Ubuntu packages
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - openjdk-8-jdk
 
    - name: install maven on your local Ubuntu machine
      become: yes
      apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
      with_items:
        - maven

    - name: create folder
      file:
        path: /home/ubuntu/tomcat
        state: directory
        mode: 0755
        owner: ubuntu
        group: ubuntu
    - name: Download Tomcat
      get_url: url=https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.8/bin/apache-tomcat-9.0.8.tar.gz dest=/home/ubuntu/tomcat
    - name: extract archive
      become: yes
      unarchive: src=/home/ubuntu/tomcat/apache-tomcat-9.0.8.tar.gz dest=/home/ubuntu/tomcat remote_src=yes
    - name: start apache
      become: yes
      shell: /home/ubuntu/tomcat/apache-tomcat-9.0.8/bin/startup.sh
